server:
  port: 8010

spring:
  application:
    name: simple-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  security.enabled: false
