server:
  port: 8000
spring:
  application:
    name: file-upload-v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.hiberate: INFO
    org.hiberate.type.descriptor.sql.BasicBinder: TRACE
    org.hiberate.type.descriptor.sql.BasicExtractor: TRACE

management:
  security.enabled: false

## INFO
info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    version: ${project.version}
    java:
      source: ${java.version}
      target: ${java.version}
      vendor: ${java.specification.vendor}