zuul:
  add-host-header: false
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    api-auth:
      path: /api/auth/**
      url: forward:/auth/
    api-cms:
      path: /api/cms/**
      url: http://192.168.4.224/api/cms/
    cms-page:
      path: /cms/**
      url: http://192.168.4.224/cms/
    3rd-route:
      path: /3rd/**
      url: forward:/3rd
    login-js-route:
      path: /js/login.js
      url: forward:/
    gt-js-route:
      path: /js/gt.js
      url: forward:/
    login-html:
      path: /**/*.html
      url: forward:/
    login-request:
      path: /login/**
      url: forward:/login

spring:
  session:
    store-type: redis
    redis:
      namespace: zuul-kanmengou
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.4.209:6579,192.168.4.236:6479,192.168.4.209:6479,192.168.4.222:6479,192.168.4.236:6579,192.168.4.222:6579
