server:
  port: 8020

spring:
  application:
    name: simple-consumer-movie-feign-hystrix-fallback-stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

feign.hystrix.enabled: true

turbine:
  appConfig: simple-consumer-movie-feign-hystrix-fallback-stream, simple-consumer-movie
  clusterNameExpression: "'default'"