server:
  port: 8040
spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    instanceId: ${spring.application.name}#${spring.cloud.client.ipAddress}:${server.port}

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  readTimeout: 60000
  connectTimeout: 60000
  maxAutoRetries: 0
  maxAutoRetriesNextServer: 1
  eureka:
    enabled: true

zuul:
  add-host-header: true
  sensitive-headers:
  prefix: /api
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

management:
  context-path: /admin
  security.enabled: false

info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    version: ${project.version}
    java:
      source: ${java.version}
      target: ${java.version}
      vendor: ${java.specification.vendor}
