server:
  port: 8040
spring:
  application:
    name: gateway-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true

zuul:
    add-host-header: true
    sensitive-headers:
    prefix: /api

management:
  context-path: /admin
  security.enabled: false

info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    version: ${project.version}
    java:
      source: ${java.version}
      target: ${java.version}
      vendor: ${java.specification.vendor}
