server:
  port: 9761

spring:
  application:
    name: spring-cloud-zuul-with-security
  mvc:
    favicon:
      enabled: false
  profiles:
    active: prod

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  readTimeout: 60000
  connectTimeout: 60000
  maxAutoRetries: 0
  maxAutoRetriesNextServer: 1
  eureka:
     enabled: false

zuul:
  add-host-header: false
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    api-auth:
      path: /api/auth/**
      url: forward:/auth/
    api-cms:
      path: /api/cms/**
      url: http://cmstest.ido-love.com/api/cms/
    cms-page:
      path: /cms/**
      url: http://cmstest.ido-love.com/cms/
    3rd-route:
      path: /3rd/**
      url: forward:/3rd
    login-js-route:
      path: /js/login.js
      url: forward:/
    gt-js-route:
      path: /js/gt.js
      url: forward:/
    login-html:
      path: /**/*.html
      url: forward:/
    login-request:
      path: /login/**
      url: forward:/login
  debug:
    request: true
  include-debug-header: true

management:
  context-path: /manage
  port: 13579

endpoints:
  actuator:
    enabled: true
  metrics:
    sensitive: true
    enabled: true
  health:
    sensitive: true
    enabled: true

info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    version: ${project.version}
    java:
      source: ${java.version}
      target: ${java.version}
      vendor: ${java.specification.vendor}

