server:
  port: 8040
spring:
  application:
    name: gateway-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.7.126:8761/eureka/,http://192.168.7.113:8761/eureka/,http://192.168.7.113:8762/eureka/
    instance:
      prefer-ip-address: true

zuul:
    add-host-header: true

management:
  context-path: /admin
  security.enabled: false

info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    version: ${project.version}
    java:
      source: ${java.version}
      target: ${java.version}
      vendor: ${java.specification.vendor}
